### ISSUE TITLE
java version

### ISSUE THREAD

**Issue by CryLegende** [PiglinDevelopment/SkinOverlay#1]
Hello, the plugin was compiled in a recent version of java so it can't work on older versions of the game (1.7 -> 1.12)

org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: dev/piglin/skinoverlay/SkinOverlay has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 52.0

thank you for your help ^^

**Comment by Iaiao** [comment]
Removed older versions from supported.
